kind: pipeline
name: build-spring-config-server

#platform:
#  os: linux
#  arch: amd64

steps:
  - name: publish
    image: plugins/docker
    settings:
      auto_tag: true
      username: thiagotafs
      password: 1a2b3c4d5e
      repo: thiagotafs/spring-config-server
      tags: latest
    when:
      event:
        - push
        - tag
#pipeline:
#  build:
#    image: java:openjdk-8-alpine
#    commands:
#      - ./mvnw clean install
#  publish:
#    image: plugins/docker
#    repo: foo/bar
#    tags: latest
#  telegram:
#    image: appleboy/drone-telegram
#    token: xxxxxxxxxx
#    to: telegram_user_id
